# Site settings
baseurl = ""
languageCode = "pl"
title = "Poukładane"
theme = "hugo-highlights-theme"

relativeurls = true

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[markup.goldmark.renderer]
unsafe = true

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Sylwia Ćwiek-Górska"
  description = "Your Description"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "pracowniapoukladane@gmail.com"

  # Hero Section
  [params.hero]
    title = "Poukładane"
    description = "Pracownia psychologiczna"
    buttonText = "Dowiedz się więcej"

  # intro section
  [params.intro]
    enable = true
    description = """Zmiany towarzyszą nam na różnych etapach naszego życia.
      <br/>
      Na różnych poziomach życia mamy potrzebę ładu.
      Ładu na biurku, przy którym na co dzień pracujemy.
      Ładu w szafie, torebce, samochodzie.
      Układamy ubrania, poduszkę przed snem, układamy sobie relacje w pracy, z bliskimi, w domu.
      <br/>
      W końcu potrzebujemy ładu w głowie, aby wiedzieć, w którym kierunku się zmierza,
      by było to bardziej nasze, nieprzypadkowe, poukładane."""

  # about section
  [params.about]
    enable = true
    title = "O mnie"
    description = """Jestem psychoterapeutką w procesie certyfikacji.
    Pracuję integracyjnie, łącząc podejście ericksonowskie z myśleniem systemowym.
    Należę do sekcji psychoterapii Polskiego Towarzystwa Psychologicznego
    i Polskiego Towarzystwa Psychiatrycznego.
    Poddaję swoją pracę regularnej superwizji u certyfikowanego superwizora w Polskim Instytucie Ericksonowskim.
    <br/>
    <br/>
    Lubię pracować metaforą, opierać się na zasobach i budujących doświadczeniach osób,
    które do mnie trafiają, przyglądać się przekazom rodzinnym, które noszą.
    Mam doświadczenie pracy z osobami pragnącymi dokonać zmian w swoim życiu,
    dotkniętymi szeroko rozumianą stratą, osobami neuroróżnorodnymi i nieheteronormatywnymi.
    Ci, którzy trafiają do mnie, mogą czuć się bezpiecznie mówiąc o swoich uczuciach,
    działaniach, dzielić się swoimi myślami.
    Nawet jeśli są one dla nich trudne lub w danej chwili niezrozumiałe.
    <br/>
    <br/>
    Wierzę, że nie ma uniwersalnych rozwiązań.
    Ten sam problem dla dwóch różnych osób może stanowić inne wyzwanie.
    W inny sposób też może być przez nie, tak samo skutecznie, rozwiązany.
    Wierzę, że osoba, która przychodzi na psychoterapię potrafi dojść do tego, czego potrzebuje,
    a największe zmiany dokonują się poza gabinetem."""
    buttonText = "Dalej"

  [params.about2]
    enable = true
    description = """<br/>
      Moje doświadczenie zawodowe:
      <br/>
      • Poukładane. Pracownia Psychologiczna
      <br/>
      • Pomorskie Centrum Terapeutyczne
      <br/>
      • Gdańskie Stowarzyszenie Epileptyków
      <br/>
      • Wojewódzki Szpital Psychiatryczny
      <br/>
      • Sopocki Ośrodek Specjalistyczny
      <br/>
      • Dom Hospicyjny im. św. Józefa w Sopocie
      <br/>
      • Miejski Ośrodek Pomocy Rodzinie w Gdańsku
      <br/>
      • Stowarzyszenie 'Światło i Cienie'"""
    buttonText = "Dalej"
    # the picture is storead at static/images/
    picture = "header.jpg"

  # skill section
  [params.skill_list]
    enable = true
    title = "Jak zacząć?"
    description = """Pierwsze spotkania mają charakter konsultacyjny —
      to jest moment, żeby zebrać ogólny wywiad, porozmawiać o tym,
      jak wygląda obecna sytuacja, co chciałoby się osiagnać, co jest możliwe
      do osiągnięcia w procesie psychoterapii.
      To jest też czas na zapoznanie się pacjenta i psychoterapeuty,
      sprawdzenie na ile możliwe jest by poczuć się bezpiecznie i mówić otwarcie o sobie,
      poznać styl pracy psychoterapeuty, zadać pytania.
      <br/>
      <br/>
      Po okresie konsultacyjnym (zwykle 1–4 spotkań),
      kiedy zostaną omówione ramy spotkań, można rozpocząć psychoterapię."""
    buttonText = "Dalej"
    # the picture is storead at static/images/
    # picture = "pic02.jpg"

    # [[params.skills]]
    #   icon = "fa-camera-retro"
    #   title = "Magna Etiam"

    # [[params.skills]]
    #   icon = "fa-pencil"
    #   title = "Lorem Ipsum"

    # [[params.skills]]
    #   icon = "fa-code"
    #   title = "Nulla Tempus"

    # [[params.skills]]
    #   icon = "fa-coffee"
    #   title = "Sed Feugiat"

  [params.offer]
    enable = true
    title = "Cennik"
    description = """Konsultacja psychologiczna 50 min<br/>(pierwsze spotkanie) • 220 zł
      <br/>
      <br/>
      Spotkanie indywidualne 50 min<br/>(po konsultacji) • 220 zł"""

  # infos section
  [params.infos]
    enable = true
    title = "Kontakt"
    description = """<strong>
      POUKŁADANE. PRACOWNIA PSYCHOLOGICZNA
      <br/>
      Sylwia Ćwiek-Górska
      </strong>
      <br/>
      <br/>
      ul. Wassowskiego 6/1
      <br/>
      80–225 Gdańsk
      """
    email = "pracowniapoukladane@gmail.com"
    phone = "+48 603 132 616"
    facebook = "https://facebook.com/poukladanepracowniapsychologiczna/"
    # the picture is storead at static/images/
    # picture = "pic03.jpg"

  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form

  [params.footer]
    enable = false
    title = "Get in Touch"

    # contact form
    [params.footer.contact]
      enable = false

    [params.footer.contact.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttonText = "send message"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "#"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "https://facebook.com/poukladanepracowniapsychologiczna"

      # [[params.footer.social]]
      #   title = "Instagramm"
      #   icon = "fa-instagram"
      #   link = "#"

      # [[params.footer.social]]
      #   title = "Dribbble"
      #   icon = "fa-dribbble"
      #   link = "#"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "mailto:pracowniapoukladane@gmail.com"

    # copyright
    # [params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© Poukładane"

      [[params.footer.copyright.notice]]
        text = "Design: [HTML5UP](//html5up.net)"

      [[params.footer.copyright.notice]]
        text = "Zdjęcia: [Unsplash](//unsplash.com/)"
